### ISSUE TITLE
Missing Arduino sketch file

### ISSUE THREAD

**Issue by dwightkelly** [DCC-EX/BaseStation-EX#10]
README.md mentions a sketch file that is missing

To utilize this sketch, simply download a zip file of this repository and open the file **DCCpp_Uno.ino** within the DCCpp_Uno folder using your Arduino IDE.

**Comment by FrightRisk** [comment]
Thanks Dwight, we will have to correct the readme and also determine a way to download an arduino IDE friendly method of doing this. One way is to rename the src folder to a name that matches the name of the project. So if the name of the main file is DCCpp, then the folder should be changed to DCCpp because the Arduino IDE is hard-coded that way. We also have to rename our DCCpp.cpp file to DCCpp.ino. I'll have to see what if anything that does to all of us who develop the software since we use PlatformIO. The other way is to write something that automates copying things to a different folder in the repositories. It would rename the main file and perhaps copy libraries. Anyone with opinions on this join in and we can get that working.

**Comment by FrightRisk** [comment]
This is now finished. The PlatformIO "src" folder was renamed using the Arduino convention of forcing the folder name for a sketch to have the same name as the main sketch file and having the main sketch file to be named  with a .ino extension in stead of the normal .cpp extension. We then changed PlatformIO.ini file to recognize the new folder name as the location for source files. You can also then tell PlatformIO to recognize a .ino file as a .cpp source file to get rid of the warning that it doesn't know what to do with a .ino file
